PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE AREA(NAME TEXT  NOT NULL,MEMO TEXT  NOT NULL,KR INTEGER,KB INTEGER,ORDERID INTEGER,NODECOUNT INTEGER);
CREATE TABLE SCHEDULE(STARTTIME INTEGER,ENDTIME INTEGER,DESCRIPTION TEXT,STATUS INTEGER,AREALIST TEXT,MODIFYTIME INTEGER,MAXSQUENCE INTEGER,CURRENTSQU INTEGER,CURRSQULEFTTIME INTEGER);
CREATE TABLE TASK(SCHEDULEID INTEGER,SEQUENECE INTEGER, MODELID INTEGER,DURING FLOAT);


CREATE TABLE TIMESPAN(Span INTEGER);
INSERT INTO "TIMESPAN" VALUES(1);
CREATE TABLE SENDSETTING(SENDTIMES INTEGER,BROADCAST INTEGER,SENDCONFIRM INTEGER);
INSERT INTO "SENDSETTING" VALUES(1,0,0);
CREATE TABLE SERVERNAME(SERVERNAME text NOT NULL);
INSERT INTO "SERVERNAME" VALUES('++++++Server+ID++++++');
CREATE TABLE USERS(USERNAME TEXT  NOT NULL,PASSWD TEXT  NOT NULL,ROLE INTEGER);
INSERT INTO "USERS" VALUES('admin','admin',2);
CREATE TABLE NODES(MAC TEXT  NOT NULL,MEMO TEXT  NOT NULL,AREA INTEGER,TYPE INTEGER, MAXSPEED FLOAT, MAXDISTANCE FLOAT,PULSES FLOAT,CURRENT1 FLOAT, CURRENT2 FLOAT,CURRENT3 FLOAT,CURRENT4 FLOAT,ISVALID INTEGER);
CREATE TABLE CALIBERATE(NODEID INTEGER,CHANNEL INTEGER, LEDS INTEGER, PWM FLOAT,CURRENTMA FLOAT);
CREATE TABLE "MODE"(NAME TEXT  NOT NULL,TYPE INTEGER,PPF1 FLOAT,PPF2 FLOAT,PPF3 FLOAT,PPF4 FLOAT,MOTORMODE INTEGER,DIRECTION INTEGER,SPEED FLOAT,DISTANCE FLOAT);
INSERT INTO "MODE" VALUES('CloseAll',0,0.0,0.0,0.0,0.0,0,0,0.0,0.0);
INSERT INTO "MODE" VALUES('Idle',0,5.0,0.0,0.0,0.0,0,0,0.0,0.0);
INSERT INTO "MODE" VALUES('!!!UV!!!',0,0.0,0.0,5.0,0.0,0,0,0.0,0.0);
INSERT INTO "MODE" VALUES('Default Test',0,10.0,10.0,0.0,0.0,1,0,10.0,500.0);
CREATE TABLE STATICMODE(NAME TEXT  NOT NULL,TYPE INTEGER,PPF1 FLOAT,PPF2 FLOAT,PPF3 FLOAT,PPF4 FLOAT,MOTORMODE INTEGER,DIRECTION INTEGER,SPEED FLOAT,DISTANCE FLOAT);
INSERT INTO "STATICMODE" VALUES('Demo Mode 1',0,10.0,10.0,0.0,0.0,1,0,10.0,500.0);
INSERT INTO "STATICMODE" VALUES('Demo mode 2',0,10.0,0.0,0.0,0.0,1,0,10.0,500.0);
INSERT INTO "STATICMODE" VALUES('Demo mode 3',0,0.0,10.0,0.0,0.0,1,0,10.0,500.0);
CREATE TABLE COMMLOG(DATETIME INTEGER  NOT NULL,ENDTIME INTEGER  NOT NULL,MODELID INTEGER,MODELNAME TEXT, AREAID INTEGER,AREANAME TEXT,PPF1 FLOAT,PPF2 FLOAT,PPF3 FLOAT,PPF4 FLOAT,OPTIONTYPE INTEGER,TIMESTOPED INTEGER);
CREATE TABLE BACKDB(DATETIME TEXT  NOT NULL,DBNAME TEXT);
CREATE TABLE USERLOG(USERNAME TEXT  NOT NULL,IP TEXT,LOGTIME INTEGER,LOGTYPE INTEGER,LOGRESULT TEXT);
CREATE INDEX IDX_ORDERID ON AREA(ORDERID);
COMMIT;

